from models.SIRM_deterministic import SIRM_deterministic
from models.SIRM_deterministic_T2 import SIRM_deterministic_T2
from models.SIRM_deterministic_per_country import SIRM_deterministic_per_country
from models.SIRM_deterministic_per_country_date_1_T2_ver_1 import SIRM_deterministic_per_countr_date_1_T2_ver_1
from models.SIRM_deterministic_per_country_date_1_T2 import SIRM_deterministic_per_countr_date_1_T2
from models.SIRM_deterministic_per_country_date_1 import SIRM_deterministic_per_countr_date_1
from models.SIRM_deterministic_per_country_date_1_ver_1 import SIRM_deterministic_per_countr_date_1_ver_1




